project_id = "pdizasxzcxurlfevzxtg"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.robotevents-proxy]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.contact]
    verify_jwt = false
